Add Ory Kratos Integration.
Improwised/golang-api pull request #198
Opened 2024-01-16 07:35 UTC by Shaktizala

Closes #193 

## Changes proposed
- Kratos Integration 
- Endpoint for Kratos redirecting and storing user details in the database.
- Kratos service in docker compose and kratos database in the same PostgreSQL server.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2024-01-16 09:05 UTC, munir131 requested changes

2024-01-16 09:05 UTC, munir131 commented on pkg/kratos/readme.md
> +You have to provide Kratos with your UI endpoint URLs, Kratos will redirect to those endpoints by initializing the flow.
@Shaktizala What frontend has to sent? Should it work with ajax request? Does it need to follow any xml/json format? Or it is form?

2024-01-16 09:30 UTC, Shaktizala commented on pkg/kratos/readme.md
> +You have to provide Kratos with your UI endpoint URLs, Kratos will redirect to those endpoints by initializing the flow.
Yes, it is in form.

2024-01-16 09:38 UTC, Shaktizala commented on config/kratos.go
> +	PublicUrl  string `envconfig:"SERVE_PUBLIC_BASE_URL"`
Both are same, it's the kratos base url, but as kratos requires envs to be in specific format it is kept like, "SERVE_PUBLIC_BASE_URL".

2024-01-16 09:41 UTC, Shaktizala commented on controllers/api/v1/auth_controller.go
> +		Expires: time.Now().Add(24 * time.Hour),
For that, we need to fix the format of entering it from env.

2024-01-16 09:49 UTC, Shaktizala commented on controllers/api/v1/auth_controller.go
> +		Expires: time.Now().Add(24 * time.Hour),
or should I take it in hours?

2024-01-16 12:21 UTC, munir131 commented on controllers/api/v1/auth_controller.go
> +	kratosID := c.Locals(constants.KratosID)
@Shaktizala Is it middleware? Middleware shouldn't be in controller

2024-01-16 12:22 UTC, munir131 commented on pkg/kratos/readme.md
> +You have to provide Kratos with your UI endpoint URLs, Kratos will redirect to those endpoints by initializing the flow.
Then please document that or add link of external doc

2024-01-16 12:28 UTC, munir131 commented on controllers/api/v1/auth_controller.go
> +	c.Next()
@Shaktizala What is purpose of it? L154 will already redirect on UI

2024-01-16 12:33 UTC, Shaktizala commented on pkg/kratos/readme.md
> +You have to provide Kratos with your UI endpoint URLs, Kratos will redirect to those endpoints by initializing the flow.
okay will update it.

2024-01-16 12:34 UTC, Shaktizala commented on controllers/api/v1/auth_controller.go
> +	c.Next()
sorry, forgot to remove it, it was there when I was not doing redirection. will update it.

2024-01-23 06:42 UTC, munir131 submitted a review, later dismissed

2024-01-23 12:25 UTC, pratikbgit requested changes
- [x] Define step pkg/kratos/oidc then run base64 -w 0 google.schema.jsonnet
- [ ] Mention the steps for OAuth 2.0 client IDs and redirect URLs set.
- [ ] Start service in on go, like Kratos up command then migrate up then api run etc.
- [x] Info: If the password field is not required, then please remove it.

2024-01-23 12:31 UTC, Shaktizala commented
> - [ ] Define step pkg/kratos/oidc than run `base64 -w 0 google.schema.jsonnet` 
> - [ ] Mention steps of OAuth 2.0 Client IDs and redirect url set.
> - [ ] Start service in on go like Kratos up command then migrate up then api run etc.
> - [ ] info : If password filed is not required then please remove it.
>  
> 
> 

@pratikbgit Password field is required, when kratos is not enabled We have to use authentication using password so at that time we need to store password.


I am not getting the 3rd statement, can you please elaborate.

CC: @munir131

2024-01-23 12:40 UTC, pratikbgit commented
> > * [ ]  Define step pkg/kratos/oidc than run `base64 -w 0 google.schema.jsonnet`
> > * [ ]  Mention steps of OAuth 2.0 Client IDs and redirect url set.
> > * [ ]  Start service in on go like Kratos up command then migrate up then api run etc.
> > * [ ]  info : If password filed is not required then please remove it.
> 
> @pratikbgit Password field is required, when kratos is not enabled We have to use authentication using password so at that time we need to store password.
> 
> I am not getting the 3rd statement, can you please elaborate.
> 
> CC: @munir131

While kratos service start before that migrate and api service should start not manually.

2024-01-30 07:17 UTC, Shaktizala commented
> > > * [ ]   Define step pkg/kratos/oidc than run `base64 -w 0 google.schema.jsonnet`
> > > * [ ]   Mention steps of OAuth 2.0 Client IDs and redirect url set.
> > > * [ ]   Start service in on go like Kratos up command then migrate up then api run etc.
> > > * [ ]   info : If password filed is not required then please remove it.
> > 
> > 
> > @pratikbgit Password field is required, when kratos is not enabled We have to use authentication using password so at that time we need to store password.
> > I am not getting the 3rd statement, can you please elaborate.
> > CC: @munir131
> 
> While kratos service start before that migrate and api service should start not manually.

@pratikbgit 
I discussed this with @munir131.
- [ ] We will have to make one script file for starting all three services.
- [ ] There is no need to remove the password field, as it is required when we are not using Kratos.
- [ ] I will add a link to the steps of creating a client ID, secrets, and different details of it.

2024-02-05 07:18 UTC, munir131 submitted a review, later dismissed

2024-02-05 07:19 UTC, munir131 commented
@Shaktizala Please resolve conflicts

2024-02-05 08:17 UTC, munir131 approved these changes

2024-02-05 08:17 UTC, merged