feat: flipt feature added for feature enable and disable
Improwised/golang-api pull request #227
Opened 2024-07-19 07:59 UTC by NiravThumar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2024-07-22 14:18 UTC, munir131 requested changes

2024-07-22 14:18 UTC, munir131 commented on cli/api.go
> +				logger.Error("Error while initlize client", zap.Error(err))
@NiravThumar Typo in initialize

2024-07-22 14:18 UTC, munir131 commented on docker-compose.yaml
> +      - "./flipt.yml:/flipt.yml"
@NiravThumar Please add sample flipt.yml too for easy setup

2024-07-23 10:36 UTC, NiravThumar commented on cli/api.go
> +				logger.Error("Error while initlize client", zap.Error(err))
done

2024-07-23 10:36 UTC, NiravThumar commented on docker-compose.yaml
> +      - "./flipt.yml:/flipt.yml"
done

2024-07-23 12:27 UTC, munir131 approved these changes

2024-07-24 06:30 UTC, merged